### ISSUE TITLE
Does this work on debian 11?

### ISSUE THREAD

**Issue by fwuffyboi** [Rabbit-Company/Passky-Server#11]
Hi, I recently tried to install this by following the instructions listed in the "readme.md" file. I installed docker with the following:
`# Install docker
curl -sSL https://get.docker.com/ | CHANNEL=stable bash
#Start docker on boot
sudo systemctl enable --now docker
#Install docker compose
sudo apt-get install libffi-dev libssl-dev
sudo apt install python3-dev
sudo apt-get install -y python3 python3-pip
sudo pip3 install docker-compose`

I then ran this commands: 
`wget https://github.com/Rabbit-Company/Passky-Server/releases/latest/download/passky-server.tar.xz
tar -xf passky-server.tar.xz
cd passky-server
#Makes installers executable
chmod +x installer.sh installerGUI.sh
#Start the GUI installer
./installerGUI.sh
#After you complete with installer you can create containers with below command
sudo docker-compose up -d`

when i ran those, I got this stack trace:
`raspi-server@raspi-server:~/passky-server $ sudo docker-compose up -d
Pulling passky-database (rabbitcompany/passky-database:latest)...
latest: Pulling from rabbitcompany/passky-database
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

I am running Debian 11 Lite(server OS basically), on a Raspberry PI 4B+ 4GB ram. This is a fresh OS install.

**Comment by zigazajc007** [comment]
Hello,

It seems that you are using 32bit OS (linux/arm/v7), while Passky has been only compiled for 64bit OS (linux/arm64/v8).

So there are two option to solve this problem.

## Option 1:
### Compile Passky Server on your own.
1. Download all files
```yml
git clone https://github.com/Rabbit-Company/Passky-Server.git
cd Passky-Server
```
2. Now you can see that there is a file named "docker-compose-build-from-source.yml", so we can remove current "docker-compose.yml" file and replace it with the "docker-compose-build-from-source.yml"
```yml
mv docker-compose-build-from-source.yml docker-compose.yml
```
3. You can now do the same as you do normally (Go thru installer and spin up docker with docker-compose up -d)

## Option 2:
### Install 64bit OS for your Raspberry PI 4B+
I would personally go with Raspberry Pi OS Lite, as this is the fork of a Debian with better hardware support for Raspberry PI.
Also make sure you choose 64bit version.

![image](https://user-images.githubusercontent.com/44822563/175226304-c4ffba0d-8832-4155-908a-03944f468cae.png)

Link to download page: https://www.raspberrypi.com/software/operating-systems/
Link to direct download: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-04-07/2022-04-04-raspios-bullseye-arm64-lite.img.xz
