### ISSUE TITLE
[SECURITY] php.ini expose_php enabled?

### ISSUE THREAD

**Issue by f0xcb** [Rabbit-Company/Passky-Server#13]
I only had the one question. Why is expose_php enabled?  Enabling expose_php for API support is a stupid idea because APIs can be used through JSON or what ever. Please dont feel attact, best regards.

Why you activated expose_php? Enabling expose_php for API support is a stupid idea, in my opinion because APIs can be used through JSON or what ever.

**Comment by zigazajc007** [comment]
Hello,

expose_php (https://www.php.net/manual/en/ini.core.php#ini.expose-php)
will only provide the version of PHP inside HTTP header. This does not affect the security.

Passky Server in version v7.0.0 also includes Admin Panel, so you can manage the accounts.
