### ISSUE TITLE
How do you decrypt without store the nonce into DB ?

### ISSUE THREAD

**Issue by 4n93L** [Rabbit-Company/Passky-Server#23]
Hello, Good Job, the asswordManager is good! and the code is clear but,
I wonder, how can you decrypt encrypted data without storing any nonce with XChaCha20?
Isn't it mandatory?
you have no "loss" of data?

**Comment by zigazajc007** [comment]
Hello,

Nonce is automatically added / appended to the end of the encrypted message. So we do not need to use additional column in a database.
