### ISSUE TITLE
Passky Self-host Admin login

### ISSUE THREAD

**Issue by WuMaKu84** [Rabbit-Company/Passky-Server#57]
Hi there :)

Sorry, either I am really to stupid or whatever, but I've deployed a self-hosted server and am totally lost in how to log in...
Am I supposed to create a user on your website to log in to my local instance?! If so, there is no possibilty to run passky in a closed network?
thanks for clarifying!

**Comment by zigazajc007** [comment]
Hello,

I would suggest you to watch this quick video: https://www.youtube.com/watch?v=kgIVnNktsX4

You can skip the process of installation for Passky Server.

**Comment by WuMaKu84** [comment]
Thanks alot, I missed the Environment Variable on the deployment using portainer... and after the creation, the variable couldn't been chosen anymore, so I had to create it again!
many thanks for the fast response, highly appreciated!!
