### ISSUE TITLE
[Question] How to install Passky Server with GUI on a shared Web hosting plan?

### ISSUE THREAD

**Issue by vzool** [Rabbit-Company/Passky-Server#8]

**Comment by zigazajc007** [comment]
# Requirements
1. At least PHP 8.0
2. At least MySQL 8.0 or MariaDB

# Setup

## Database

### Web Panel
1. Create the user with strong password and **DON'T** allow remote connection. (Don't use %, but rather use 127.0.0.1)
2. Create database named passky
3. Give all permissions for created user to the database named passky
4. Create all tables. SQL code is located [HERE](https://github.com/Rabbit-Company/Passky-Server/blob/main/database/database.sql).
### Manually
```sql
# Make sure you change somePassword to a complicated password.
CREATE USER 'passky'@'127.0.0.1' IDENTIFIED BY 'somePassword';
# Create database named passky
CREATE DATABASE passky;
# Give all permissions for user passky to the database named passky  
GRANT ALL PRIVILEGES ON passky.* TO 'passky'@'127.0.0.1' WITH GRANT OPTION;
```
Last step is to create all tables. SQL code is located [HERE](https://github.com/Rabbit-Company/Passky-Server/blob/main/database/database.sql).

| :warning: WARNING |
|:---------------------------|
| If you have used different database and user name, make sure to change code accordingly. Don't forget to also change the SQL code copied from [database.sql](https://github.com/Rabbit-Company/Passky-Server/blob/main/database/database.sql) file. |

## API
1. Upload all files and folders from [api/src](https://github.com/Rabbit-Company/Passky-Server/tree/main/api/src) directory to your root folder of the website (Usually called public_html).
2. Create 2 additional files called **api-limiter.json** and **tokens.json** one folder behind public_html folder with a json content:
```json
{}
```
| :warning: WARNING |
|:---------------------------|
| **api-limiter.json** and **tokens.json** files can't be located in public_html folder as they shouldn't be visible to the public. |

3. Open Settings.php file located in public_html folder and change settings under "DATABASE SETTINGS" category. Other settings are optional.

| :warning: WARNING |
|:---------------------------|
| If your database name is not 'passky', then you would also need to change the database name in Database.php and User.php files where 'dbname=passky' is located (you can use Ctrl + F to quickly find those).|

4. Install dependencies located [HERE](https://github.com/Rabbit-Company/Passky-Server/blob/main/api/composer.json) thru composer. Shared Hosting providers should provide you access to the composer. 

## Testing
Now you can open the website and it should inform you if any major mistake was detected. But keep in mind that those mistakes are currently only based for docker deployment. So it will inform you about insecure connection or if API doesn't have access to the database, but it won't inform you if composer dependencies weren't installed or any other mistake that isn't present thru docker-compose installaion.

I will focus on shared hosting more and will also make installation easier in the near future.

**Comment by CMB244** [comment]
sorry, this is just for testing purpose

**Comment by zigazajc007** [comment]
Documentation is now available here: https://github.com/Rabbit-Company/Passky-Server/blob/main/docs/installation/shared-hosting.md
